---
title: "BTC Market Cap"
author: Scott Goley
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    theme: journal
    vertical_layout: scroll
---

```{r setup, include=FALSE}

library(Quandl)
library(scales)
library(ggplot2)
library(highcharter)
library(dplyr)
library(magrittr)
library(xts)

bitstamp <- Quandl("BCHARTS/BITSTAMPUSD")
btce <- Quandl("BCHARTS/BTCEUSD")
mktcp <- Quandl("BCHAIN/MKTCP")

mktcp %>%
  rename(Daily = Date) -> mktcp
mktcp$Weekly <- as.Date(cut(mktcp$Daily,breaks="week"))
mktcp$Monthly <- as.Date(cut(mktcp$Daily,breaks="month"))

```

Inputs {.sidebar}
-----------------------------------------------------------------------

### Input Variables

```{r}

selectInput('dateperiod',
            label = 'Time Period',
            choices = c("Daily","Weekly","Monthly"),
            selected = 'Daily'
)

period_frame <- reactive({ mktcp[,c(input$dateperiod,"Value")] %>% set_colnames(c("Date","Value"))
})



```

Column
-----------------------------------------------------------------------

### Bitcoin Market Cap


```{r}

renderHighchart(hchart(xts(period_frame()$Value,order.by = period_frame()$Date)) %>%
             hc_add_theme(hc_theme_538())
           )

```
